### ISSUE TITLE
Update for new auth

### ISSUE THREAD

**Issue by Marzia2** [wizzzz9/steampy_rework#2]
Привет, насколько я слышал вышел новый метод авторизации для Steam, и теперь веб сессия не рефрешится ккак раньше, есть ли возможность обновить библиотеку ?

**Comment by wizzzz9** [comment]
Добрый день, все верно, но насколько я сейчас вижу, проблем с созданием сессий нет, а касаемо обновлений сессии, в библиотеке нет такого функционала, если вы пробуете использовать мертвую сессию, то библиотека не пытается ее обновить, а просто создает новую, по этому очень важно, даже если вы подгружаете сессию использовать метод login у SteamClient, этот метод сразу же проверяет живая ли сессия, если нет, то он инициирует новую авторизацию и авторизовывается.

**Comment by wizzzz9** [comment]
Возможно в будущем добавлю новый метод авторизации, в котором сессия не будет умирать вообще, но на данный момент особо нет времени, да и на мой взгляд в этом нет смысла

**Comment by Marzia2** [comment]
Понял, спасибо, да пока проблем не наблюдаю
