### ISSUE TITLE
can you fix ConfirmationExpected

### ISSUE THREAD

**Issue by iBuyPower47** [wizzzz9/steampy_rework#3]

**Comment by Marzia2** [comment]
Короче, это такой хот фикс, ибо там нужно много переписать, изменили url для получения конфирмов https://steamcommunity.com/mobileconf/conf -> https://steamcommunity.com/mobileconf/getlist
 Так же теперь информация отдается в виде json а не html, теперь для подтверждения трейда нужны параметры id и nonce запрос для самого подтверждения не изменился только теперь cid = id, ck = nonce. Данная информация больше для кодеров чем для простых работяг
